namespace Jellyfin.Database.Providers.Postgres.Services.Models;

/// <summary>Summary of a slow query captured from <c>pg_stat_statements</c>.</summary>
/// <param name="QueryPreview">First 120 characters of the normalized query text.</param>
/// <param name="MeanMs">Mean execution time in milliseconds.</param>
/// <param name="Calls">Total number of executions.</param>
/// <param name="TotalMs">Cumulative execution time in milliseconds.</param>
/// <param name="Rows">Average rows returned per execution.</param>
/// <param name="SharedHitPercent">Percentage of shared-buffer accesses served from PostgreSQL's cache, when applicable.</param>
/// <param name="SharedBlocksRead">Shared blocks read from disk by the statement.</param>
/// <param name="TempBlocks">Temporary blocks read or written by the statement.</param>
/// <param name="Wal">Human-readable total WAL generated by the statement.</param>
public sealed record SlowQueryInfo(
    string QueryPreview,
    double MeanMs,
    long Calls,
    double TotalMs,
    double Rows,
    double? SharedHitPercent,
    long SharedBlocksRead,
    long TempBlocks,
    string Wal);
