using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Jellyfin.Plugin.JellyTrend.Api;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Jellyfin.Database.Providers.Postgres.Services;

/// <summary>
/// Optimised PostgreSQL implementation of <see cref="IRecommendationQueryProvider"/>.
/// Uses Npgsql directly (bypassing EF Core) to issue single-pass queries with native
/// PostgreSQL array operators (<c>&amp;&amp;</c>) and GIN-indexed lookups, replacing the
/// correlated-subquery pattern generated by EF Core that caused ~45 s response times.
/// </summary>
/// <remarks>
/// <para>
/// Genres, Tags and Studios are stored pipe-delimited (<c>|</c>) in <c>BaseItems</c>.
/// We convert them to arrays with <c>string_to_array</c> so the <c>&amp;&amp;</c>
/// (overlap) operator can use GIN indexes.
/// </para>
/// <para>
/// This class is registered only when the Postgres plugin is active. If the user
/// has not installed JellyTrend, Jellyfin's DI container will not resolve
/// <see cref="IRecommendationQueryProvider"/> and this class is never instantiated.
/// </para>
/// </remarks>
public sealed class PostgresRecommendationQueryProvider : IRecommendationQueryProvider
{
    private readonly ILogger<PostgresRecommendationQueryProvider> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="PostgresRecommendationQueryProvider"/> class.
    /// </summary>
    /// <param name="logger">Logger for query diagnostics.</param>
    public PostgresRecommendationQueryProvider(ILogger<PostgresRecommendationQueryProvider> logger)
    {
        _logger = logger;
    }

    private static NpgsqlConnection OpenConnection()
    {
        var connStr = PostgresPlugin.Instance?.Configuration?.ConnectionString
            ?? throw new InvalidOperationException("PostgreSQL connection string is not configured.");
        var conn = new NpgsqlConnection(connStr);
        conn.Open();
        return conn;
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetPlayedMovies(Guid userId, int limit)
    {
        const string Sql = """
            SELECT b."Id", b."Genres", b."Tags", b."Studios", b."CommunityRating", b."PremiereDate",
                   p."ProviderValue" AS "TmdbId"
            FROM "BaseItems" b
            LEFT JOIN "BaseItemProviders" p ON p."ItemId" = b."Id" AND p."ProviderId" = 'Tmdb'
            WHERE b."Type" = 'Movie'
              AND b."IsVirtualItem" = false
              AND EXISTS (
                  SELECT 1 FROM "UserData" ud
                  WHERE ud."ItemId" = b."Id"
                    AND ud."UserId" = @userId
                    AND ud."Played" = true
              )
            ORDER BY b."DateModified" DESC
            LIMIT @limit
            """;

        return ExecuteQuery(Sql, userId, limit);
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetResumableMovies(Guid userId, int limit)
    {
        const string Sql = """
            SELECT b."Id", b."Genres", b."Tags", b."Studios", b."CommunityRating", b."PremiereDate",
                   p."ProviderValue" AS "TmdbId"
            FROM "BaseItems" b
            LEFT JOIN "BaseItemProviders" p ON p."ItemId" = b."Id" AND p."ProviderId" = 'Tmdb'
            WHERE b."Type" = 'Movie'
              AND b."IsVirtualItem" = false
              AND EXISTS (
                  SELECT 1 FROM "UserData" ud
                  WHERE ud."ItemId" = b."Id"
                    AND ud."UserId" = @userId
                    AND ud."PlaybackPositionTicks" > 0
                    AND ud."Played" = false
              )
            LIMIT @limit
            """;

        return ExecuteQuery(Sql, userId, limit);
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByGenres(
        Guid userId,
        IReadOnlyList<string> genres,
        IReadOnlyList<Guid> topParentIds,
        int limit)
    {
        if (genres.Count == 0)
        {
            return [];
        }

        var sql = BuildUnwatchedSql(
            extraWhere: """
                AND string_to_array(b."Genres", '|') && @facets
                """,
            hasTopParents: topParentIds.Count > 0);

        return ExecuteUnwatchedQuery(sql, userId, genres.ToArray(), topParentIds, limit);
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByPersons(
        Guid userId,
        IReadOnlyList<Guid> personIds,
        IReadOnlyList<Guid> topParentIds,
        int limit)
    {
        if (personIds.Count == 0)
        {
            return [];
        }

        // PeopleBaseItemMap joins on ItemId; filter by any of the given person ids.
        var sql = BuildUnwatchedSql(
            extraWhere: """
                AND EXISTS (
                    SELECT 1 FROM "PeopleBaseItemMap" pm
                    WHERE pm."ItemId" = b."Id"
                      AND pm."PeopleId" = ANY(@facets)
                )
                """,
            hasTopParents: topParentIds.Count > 0,
            facetType: NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Uuid);

        return ExecuteUnwatchedQuery(sql, userId, personIds.ToArray(), topParentIds, limit);
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetUnwatchedMoviesByTags(
        Guid userId,
        IReadOnlyList<string> tags,
        IReadOnlyList<Guid> topParentIds,
        int limit)
    {
        if (tags.Count == 0)
        {
            return [];
        }

        var sql = BuildUnwatchedSql(
            extraWhere: """
                AND string_to_array(b."Tags", '|') && @facets
                """,
            hasTopParents: topParentIds.Count > 0);

        return ExecuteUnwatchedQuery(sql, userId, tags.ToArray(), topParentIds, limit);
    }

    /// <inheritdoc/>
    public IReadOnlyList<RecommendationItem> GetRandomUnwatchedMovies(
        Guid userId,
        IReadOnlyList<Guid> topParentIds,
        int limit)
    {
        var topParentFilter = topParentIds.Count > 0
            ? "AND b.\"TopParentId\" = ANY(@topParentIds)"
            : string.Empty;

        var sql = $"""
            SELECT b."Id", b."Genres", b."Tags", b."Studios", b."CommunityRating", b."PremiereDate",
                   p."ProviderValue" AS "TmdbId"
            FROM "BaseItems" b
            LEFT JOIN "BaseItemProviders" p ON p."ItemId" = b."Id" AND p."ProviderId" = 'Tmdb'
            WHERE b."Type" = 'Movie'
              AND b."IsVirtualItem" = false
              {topParentFilter}
              AND NOT EXISTS (
                  SELECT 1 FROM "UserData" ud
                  WHERE ud."ItemId" = b."Id"
                    AND ud."UserId" = @userId
                    AND (ud."Played" = true OR ud."PlaybackPositionTicks" > 0)
              )
            ORDER BY random()
            LIMIT @limit
            """;

        try
        {
            using var conn = OpenConnection();
            using var cmd = conn.CreateCommand();
            cmd.CommandText = sql;
            cmd.Parameters.AddWithValue("userId", userId);
            if (topParentIds.Count > 0)
            {
                cmd.Parameters.Add(new NpgsqlParameter("topParentIds", NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Uuid)
                {
                    Value = topParentIds.ToArray()
                });
            }

            cmd.Parameters.AddWithValue("limit", limit);
            return ReadItems(cmd);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[JellyTrend] GetRandomUnwatchedMovies failed; returning empty list");
            return [];
        }
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────────────────────

    private static string BuildUnwatchedSql(
        string extraWhere,
        bool hasTopParents,
        NpgsqlTypes.NpgsqlDbType facetType = NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Text)
    {
        _ = facetType; // consumed by caller via the overloaded ExecuteUnwatchedQuery
        var topParentFilter = hasTopParents
            ? "AND b.\"TopParentId\" = ANY(@topParentIds)"
            : string.Empty;

        return $"""
            SELECT b."Id", b."Genres", b."Tags", b."Studios", b."CommunityRating", b."PremiereDate",
                   p."ProviderValue" AS "TmdbId"
            FROM "BaseItems" b
            LEFT JOIN "BaseItemProviders" p ON p."ItemId" = b."Id" AND p."ProviderId" = 'Tmdb'
            WHERE b."Type" = 'Movie'
              AND b."IsVirtualItem" = false
              {topParentFilter}
              {extraWhere}
              AND NOT EXISTS (
                  SELECT 1 FROM "UserData" ud
                  WHERE ud."ItemId" = b."Id"
                    AND ud."UserId" = @userId
                    AND (ud."Played" = true OR ud."PlaybackPositionTicks" > 0)
              )
            ORDER BY b."CommunityRating" DESC NULLS LAST
            LIMIT @limit
            """;
    }

    [SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "SQL is a hardcoded constant string — no user input reaches CommandText.")]
    private List<RecommendationItem> ExecuteQuery(string sql, Guid userId, int limit)
    {
        try
        {
            using var conn = OpenConnection();
            using var cmd = conn.CreateCommand();
            cmd.CommandText = sql;
            cmd.Parameters.AddWithValue("userId", userId);
            cmd.Parameters.AddWithValue("limit", limit);
            return ReadItems(cmd);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[JellyTrend] Query failed; returning empty list. SQL: {Sql}", sql);
            return [];
        }
    }

    [SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "SQL is built from hardcoded templates only; no user input reaches CommandText.")]
    private List<RecommendationItem> ExecuteUnwatchedQuery(
        string sql,
        Guid userId,
        Array facets,
        IReadOnlyList<Guid> topParentIds,
        int limit)
    {
        try
        {
            using var conn = OpenConnection();
            using var cmd = conn.CreateCommand();
            cmd.CommandText = sql;
            cmd.Parameters.AddWithValue("userId", userId);

            // Facet parameter type depends on the caller (string[] or Guid[]).
            if (facets is string[] strFacets)
            {
                cmd.Parameters.Add(new NpgsqlParameter("facets", NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Text) { Value = strFacets });
            }
            else if (facets is Guid[] guidFacets)
            {
                cmd.Parameters.Add(new NpgsqlParameter("facets", NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Uuid) { Value = guidFacets });
            }

            if (topParentIds.Count > 0)
            {
                cmd.Parameters.Add(new NpgsqlParameter("topParentIds", NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Uuid)
                {
                    Value = topParentIds.ToArray()
                });
            }

            cmd.Parameters.AddWithValue("limit", limit);
            return ReadItems(cmd);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[JellyTrend] Unwatched query failed; returning empty list. SQL: {Sql}", sql);
            return [];
        }
    }

    private static List<RecommendationItem> ReadItems(NpgsqlCommand cmd)
    {
        var results = new List<RecommendationItem>();
        using var reader = cmd.ExecuteReader(CommandBehavior.SequentialAccess);
        while (reader.Read())
        {
            var id = reader.GetGuid(0);
            var genres = SplitPipeDelimited(reader.IsDBNull(1) ? null : reader.GetString(1));
            var tags = SplitPipeDelimited(reader.IsDBNull(2) ? null : reader.GetString(2));
            var studios = SplitPipeDelimited(reader.IsDBNull(3) ? null : reader.GetString(3));
            float? rating = reader.IsDBNull(4) ? null : reader.GetFloat(4);
            DateTime? premiereDate = reader.IsDBNull(5) ? null : reader.GetDateTime(5).ToUniversalTime();
            string? tmdbId = reader.IsDBNull(6) ? null : reader.GetString(6);

            results.Add(new RecommendationItem(id, tmdbId, genres, tags, studios, rating, premiereDate));
        }

        return results;
    }

    private static string[] SplitPipeDelimited(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return [];
        }

        return value.Split('|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
    }
}
